package com.einfachgesund.kidsmoveday.model;

import jakarta.persistence.*;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import lombok.Builder;
import java.time.LocalDateTime;

/**
 * JPA Entity representing an event registration for Kids Move Day.
 *
 * <p>Maps to the 'registrations' table in PostgreSQL.
 * Supports both insured users (via User FK) and walk-in guests
 * (gastName / gastEmail fields).</p>
 *
 * <p>Covers: R7 (JPA/ORM), R9 (Builder Pattern via Lombok)</p>
 *
 * @author [FirstName LastName]
 * @version 1.0
 */
@Entity
@Table(name = "registrations")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Registration {

    /** Primary key, auto-generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The insured user who registered.
     * Null if this is a guest registration.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id")
    private User user;

    /** Number of children attending with this registration. */
    @Column(name = "kinder_anzahl", nullable = false)
    private int kinderAnzahl;

    /** Full name of the guest (used when no user account exists). */
    @Column(name = "gast_name")
    private String gastName;

    /** Email of the guest for confirmation purposes. */
    @Column(name = "gast_email")
    private String gastEmail;

    /**
     * Registration status.
     * Possible values: BESTAETIGT, STORNIERT, WARTELISTE
     */
    @Column(nullable = false)
    private String status;

    /** Timestamp of when this registration was created. */
    @Column(name = "registriert_am")
    private LocalDateTime registriertAm;

    /**
     * Automatically sets default values before persisting.
     * Covers R7 - JPA lifecycle callback.
     */
    @PrePersist
    public void prePersist() {
        this.registriertAm = LocalDateTime.now();
        if (this.status == null) this.status = "BESTAETIGT";
    }
}