package com.einfachgesund.kidsmoveday.model;

import jakarta.persistence.*;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import lombok.Builder;
import java.time.LocalDateTime;

/**
 * JPA Entity representing a registered user (Versicherungsnehmer).
 *
 * <p>Maps to the 'users' table in PostgreSQL. Used for both
 * insured members and administrators of the Kids Move Day event.</p>
 *
 * <p>Covers: R7 (JPA/ORM)</p>
 *
 * @author [FirstName LastName]
 * @version 1.0
 */
@Entity
@Table(name = "users")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class User {

    /** Primary key, auto-generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Unique insurance number assigned by EinfachGesund. */
    @Column(nullable = false, unique = true)
    private String versicherungsnummer;

    /** Hashed or plain password for login authentication. */
    @Column(nullable = false)
    private String passwort;

    /** Full name of the insured person. */
    @Column(nullable = false)
    private String name;

    /** Email address, must be unique across all users. */
    @Column(nullable = false, unique = true)
    private String email;

    /** Indicates whether this user holds an active insurance policy. */
    @Column(name = "ist_versichert")
    private boolean istVersichert = true;

    /** Role of the user: USER or ADMIN */
    @Column(name = "role")
    private String role = "USER";

    /** Timestamp of when the user account was created. */
    @Column(name = "erstellt_am")
    private LocalDateTime erstelltAm;
    /** City of residence of the insured person. */
    @Column(name = "stadt")
    private String stadt;

    /** Date of birth of the insured person. */
    @Column(name = "geburtsdatum")
    private String geburtsdatum;

    /**
     * Automatically sets the creation timestamp before persisting.
     * Covers R7 - JPA lifecycle callback.
     */
    @PrePersist
    public void prePersist() {
        this.erstelltAm = LocalDateTime.now();
    }
}